// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qVxvx_1bFEoPNtDzC2A3iNAf_Oq6g0w',
    appId: '1:437725362369:web:05e156f3c0ba08ced17c40',
    messagingSenderId: '437725362369',
    projectId: 'iot-air-quality-8005e',
    authDomain: 'iot-air-quality-8005e.firebaseapp.com',
    databaseURL: 'https://iot-air-quality-8005e-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-8005e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDr7oP1_BUIN5MM2viRiQKPQaYBlfrxpU',
    appId: '1:437725362369:android:e0c8169fb5f38d88d17c40',
    messagingSenderId: '437725362369',
    projectId: 'iot-air-quality-8005e',
    databaseURL: 'https://iot-air-quality-8005e-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-8005e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnT3jRTf_c27muFfUhnMcwADGhSiMetyE',
    appId: '1:437725362369:ios:986be1d75c6cb678d17c40',
    messagingSenderId: '437725362369',
    projectId: 'iot-air-quality-8005e',
    databaseURL: 'https://iot-air-quality-8005e-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-8005e.appspot.com',
    iosBundleId: 'com.example.iot',
  );
}
